---
- name: "Update Authentication Configuration for provider: {{ vro_auth_provider }}"
  uri:
    url: "https://{{ inventory_hostname|lower }}:{{ vro_cc_api_port }}/vco-controlcenter/api/authentication/configuration/{{ auth_provider_id }}"
    user: "{{ vro_root_username }}"
    password: "{{ vro_root_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: POST
    headers:
      Accept: "{{ http_Accept }}"
    body_format: "{{ http_body_format }}"
    body:
      CAFE:
        url: "https://{{ vro_auth_hostname }}/component-registry"
        username: "{{ vro_auth_username }}"
        password: "{{ vro_auth_password }}"
        importCertificates: true
        configureLicences: true
        adminGroup: "{{ vro_auth_adminGroup }}"
        adminGroupDomain: "{{ vro_auth_adminGroupDomain }}"
        provider: CAFE
    status_code: [200]
    timeout: 120
  register: auth_update_response
  delegate_to: localhost
  delegate_facts: true
  #changed_when: auth_update_response.status == 200

- name: "Validate Authentication Configuration for provider: {{ vro_auth_provider }}"
  uri:
    url: "https://{{ inventory_hostname|lower }}:{{ vro_cc_api_port }}/vco-controlcenter/api/authentication/configuration/validate"
    user: "{{ vro_root_username }}"
    password: "{{ vro_root_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: GET
    headers:
      Accept: "{{ http_Accept }}"
    status_code: [200]
  register: auth_pre_validate_response
  delegate_to: localhost
  delegate_facts: true

- name: "Complete Authentication Configuration Wizard for provider: {{ vro_auth_provider }}"
  uri:
    url: "https://{{ inventory_hostname|lower }}:{{ vro_cc_api_port }}/vco-controlcenter/api/authentication/configuration/{{ auth_provider_id }}/finish"
    user: "{{ vro_root_username }}"
    password: "{{ vro_root_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: POST
    headers:
      Accept: "{{ http_Accept }}"
    status_code: [200]
  register: auth_finish_response
  delegate_to: localhost
  delegate_facts: true
  changed_when: auth_finish_response.status == 200
  when: auth_pre_validate_response.json.errorMessage == "Authentication is approved. State changed to APPROVED from REGISTERED"

- name: "Validate Authentication Configuration for provider: {{ vro_auth_provider }}"
  uri:
    url: "https://{{ inventory_hostname|lower }}:{{ vro_cc_api_port }}/vco-controlcenter/api/authentication/configuration/validate"
    user: "{{ vro_root_username }}"
    password: "{{ vro_root_password }}"
    validate_certs: "{{ http_validate_certs }}"
    force_basic_auth: yes
    method: GET
    headers:
      Accept: "{{ http_Accept }}"
    status_code: [200]
  register: auth_post_validate_response
  delegate_to: localhost
  delegate_facts: true

# - name: "Remove Authentication Configuration Wizard for provider: {{ vro_auth_provider }}"
#   uri:
#     url: "https://{{ inventory_hostname|lower }}:{{ vro_cc_api_port }}/vco-controlcenter/api/authentication/configuration/unregister/{{ auth_provider_id }}"
#     user: "{{ vro_root_username | default(vro_default_root_username) }}"
#     password: "{{ vro_root_password | default(vro_default_root_password) }}"
#     validate_certs: "{{ http_validate_certs }}"
#     force_basic_auth: yes
#     method: DELETE
#     headers:
#       Accept: "{{ http_Accept }}"
#     body_format: "{{ http_body_format }}"
#     body:
#       CAFE:
#         force: true
#         username: "{{ vro_auth_username }}"
#     status_code: [200]
#   register: auth_remove_response
#   delegate_to: localhost
#   delegate_facts: true
#   changed_when: auth_remove_response == 200
#   when: auth_post_validate_response.json.status != "OK"
