---
#- include_tasks: remove_existing.yml
#  when: vro_remove_existing|bool

- include_tasks: wait_for_vro_service.yml

# - include_tasks: configure_hostname.yml

# TODO: configure logging

# - include_tasks: configure_auth_provider.yml
#   when: vro_auth_provider is defined

- include_tasks: import_ssl_certificate.yml
  when: vro_use_selfsigned_certificate|bool == False

# - include_tasks: configure_ntp.yml

- include_tasks: install_plugin.yml
  loop: "{{ vro_plugins }}"
  loop_control:
    loop_var: vro_plugin

- include_tasks: wait_for_vro_server.yml

- include_tasks: install_packages.yml
  loop: "{{ vro_packages }}"
  loop_control:
    loop_var: vro_package
  when: |
    vro_install_packages|bool and
    vro_auth_provider is defined

# - include_tasks: add_plugin_endpoints.yml
#   vars:
#     ignore_workflow_errors: "{{ vro_ignore_plugin_errors }}"
#   when: |
#     vro_configure_plugin_endpoints|bool and
#     vro_auth_provider is defined
