---
## Set the vCenter Server Product version and build if this cannot be determined
## by the provided OVF file name.
# vcsa_version: "6.5.0"
# vcsa_build: "9451637"

## Set Network Configuration for the appliance.
network_label: "Management"
network_ip_address: "10.1.10.95"
network_prefix: "24"
network_gateway: "10.1.10.254"

## Set the OVA deployment variables.
ova_deployment_hostname: "{{ management_vcenter_hostname }}"
ova_deployment_username: "{{ management_vcenter_username }}"
ova_deployment_password: "{{ management_vcenter_password }}"
ova_deployment_datacenter: "{{ management_vcenter_datacenter }}"
ova_deployment_cluster: "{{ management_vcenter_cluster }}"
ova_deployment_datastore: "vsanDatastore"
# ova_deployment_folder: "SG1/vm"

## Set the admin username to use when configurating the appliance, or leave commented out to use the default.
# vcsa_admin_username: ""

## Set the admin password for specified vcsa_admin_username, or leave commented out to use the default.
# vcsa_admin_password: ""

## Set the sso username, or leave commented out to use the default.
# vcsa_sso_username: ""

## Set the sso password, or leave commented out to use the default.
# vcsa_sso_password: ""

ansible_user: "{{ vcsa_admin_username }}"
ansible_password: "{{ vcsa_admin_password }}"
ansible_host: "{{ network_ip_address }}"


## Ensure that the following services are started on the appliance
## and set to AUTOMATIC startup.
## A list of services can be found using 'service-control --list'.
vcsa_services_to_start:
 - updatemgr
 - vsphere-ui
 - content-library
 - vapi-endpoint

## Ensure that the following services are stopped on the appliance
## and set to MANUAL startup.
vcsa_services_to_stop:
 - rbd
 - imagebuilder

## Set this to yes to prevent the VCSA root account from expiring.
# vcsa_root_expiration_disable: yes

## Set the number of days until the VCSA root account expires.
## This setting will be ignored if 'disable_root_expiration'
## is set to 'yes'.
# vcsa_root_expiration_days: "180"

## If you would like to join the appliance to the domain then
## set 'vcsa_join_to_domain' to 'yes'.
vcsa_join_to_domain: yes

# Active Directory Join Domain Account
vcsa_ad_dom_join_domain: "{{ dns_domain }}"
vcsa_ad_dom_join_username: "svc_dom_join@sgroot.local"
vcsa_ad_dom_join_password: "VMwar3!!"
# vcsa_ad_dom_join_ou: ""

##
vcsa_datacenters:
 - SG2

vcsa_clusters:
 - name: "Resources-01"
   datacenter: SG2

##
vcsa_vcenter_admin_groups:
 - "vSphere-Admins"

vcsa_vcenter_readonly_groups:
 - "vSphere-ReadOnly"