---
- include_tasks: check_file_exists.yml

- name: Fail if OVA file is not found.
  fail:
    msg: "OVA file {{ ova_filename }} not found in path {{ ova_path }}"
  when: ova_file.stat.exists|bool == False

- include_tasks: import_ova_template.yml
  when: ova_file.stat.exists|bool == True

