---
# vRO API Variables
vro_api_version: "1"

# vRO OVF/OVA Variables
ova_path: "/mnt/iso/VMware/vRO/7.5"
ova_filename: "VMware-vRO-Appliance-7.5.0.458-10110089_OVF10.ova"
ova_enable_ssh: "True"
ova_enable_telemetry: "False"
