---
- name: Add External Identity Source Name
  lineinfile:
    path: /usr/lib/vmware/cis_upgrade_runner/payload/component-scripts/sso/exported_sso.properties
    create: yes
    regexp: "^ExternalIdentitySource.{{ ad_dom_join_domain }}.name={{ ad_dom_join_domain }}$"
    line: "ExternalIdentitySource.{{ ad_dom_join_domain }}.name={{ ad_dom_join_domain }}"
  register: sso_name

- name: Add External Identity Source Type
  lineinfile:
    path: /usr/lib/vmware/cis_upgrade_runner/payload/component-scripts/sso/exported_sso.properties
    regexp: "^ExternalIdentitySource.{{ ad_dom_join_domain }}.type=0$"
    insertafter: "^ExternalIdentitySource.{{ ad_dom_join_domain }}.name={{ ad_dom_join_domain }}$"
    line: "ExternalIdentitySource.{{ ad_dom_join_domain }}.type=0"
  register: sso_type

- name: Add External Identity Source Domain Name
  lineinfile:
    path: /usr/lib/vmware/cis_upgrade_runner/payload/component-scripts/sso/exported_sso.properties
    regexp: "^ExternalIdentitySourcesDomainNames={{ ad_dom_join_domain }}$"
    insertafter: "^ExternalIdentitySource.{{ ad_dom_join_domain }}.type=0$"
    line: "ExternalIdentitySourcesDomainNames={{ ad_dom_join_domain }}"
  register: sso_domain

- name: Import SSO Identity Sources
  shell: "/bin/bash /usr/lib/vmware/cis_upgrade_runner/payload/component-scripts/sso/sso_import.sh"
  register: import_sso
  when: |
    sso_name.changed|bool or
    sso_type.changed|bool or
    sso_domain.changed|bool
