---
# - include_tasks: get_version.yml
# - include_tasks: wait_for_ssh.yml
# - include_tasks: wait_for_firstboot_operation.yml
# - include_tasks: update_root_account.yml
# - include_tasks: configure_syslog.yml

# - include_tasks: update_identity_sso_config_cli.yml

# - include_tasks: join_appliance_to_domain.yml
#   when: |
#     vcsa_join_to_domain is defined and
#     vcsa_join_to_domain|bool

# - include_tasks: add_domain_to_identity_sources.yml
#   when: |
#     (vcsa_join_to_domain is defined and vcsa_join_to_domain|bool) and
#     (ad_join is defined and ad_join.changed|bool) and
#     (vcsa_reboot is defined and vcsa_reboot.changed|bool)

- include_tasks: create_datacenters.yml
  loop: "{{ vcsa_datacenters }}"
  loop_control:
    loop_var: datacenter
  when: vcsa_datacenters is defined

- include_tasks: create_clusters.yml
  loop: "{{ vcsa_clusters }}"
  loop_control:
    loop_var: cluster
  when: vcsa_clusters is defined

# - include_tasks: assign_admin_permissions.yml

# - include_tasks: rest_api_auth_login.yml

# - include_tasks: start_vcsa_services.yml
#   when: vcsa_services_to_start is defined

# - include_tasks: stop_vcsa_services.yml
#   when: vcsa_services_to_stop is defined

# - include_tasks: rest_api_auth_logout.yml