---
## This is a global variables file that will apply to all vRO appliances.
## If you need to configure these per appliance, then copy the required variables
## to a host.yml file in host_vars to override.

## Enable SSH access to the appliance.
vro_enable_ssh: "True"

## Enable Customer Experience Improvement Program
vro_enable_telemetry: "False"

## Set the ports used by the vco and vco-controlcenter APIs.
vro_api_port: 8281
vro_cc_api_port: 8283

## Configure remote syslog server.
# vro_syslog_server: 

## Set the auth provider to use for vRO authentication.
## Auth provider is one of 'CAFE' or 'VSPHERE'.

## Uncomment these lines to enable VSPHERE Authentication.
# vro_auth_provider: VSPHERE
# vro_auth_username: administrator@vsphere.local
# vro_auth_password: VMwar3!!
# vro_adminGroup: "vro-admins"
# vro_adminGroupDomain: "{{ dns_default_domain }}"
# vro_auth_default_tenant: "vsphere.local"

## Uncomment these lines to enable vRA (CAFE) Authentication.
vro_auth_provider: CAFE
vro_auth_hostname: vra.sgroot.local
vro_auth_username: defaultadmin
vro_auth_password: VMwar3!!
vro_auth_adminGroup: "vRO_SG_Role_Admins"
vro_auth_adminGroupDomain: "{{ dns_default_domain }}"
vro_auth_default_tenant: "vsphere.local"

## Set to enable or disable if plugin endpoints should be configured.
## This will have a dependency on an authentication provider being configured
## and the API user a member of the adminGroup.
vro_configure_plugin_endpoints: yes

## Add vCenter Server Endpoints.
## If you also add the vAPI endpoint, ensure this service has been started.
vcenter_plugin_endpoints:
  - hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    domain: "{{ dns_default_domain }}"
    add_vapi_endpoint: no

## Add HTTP Restful API Endpoints.
## Supported auth_type's are Basic and OAuth2
## Uncomment and set proxy section if rest host is behind a proxy.
rest_plugin_endpoints:
  - name: 
    url: 
    auth_type: Basic
    basic_username: 
    basic_password:
    # oauth2_token: 
    # proxy_host: 
    # proxy_port: 
    # proxy_username: 
    # proxy_password: 
    host_verification: no

powershell_plugin_endpoints:
  - name: 
    host: 
    port: 
    auth_type: 
